name: raddi_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # Requests
  dio: ^5.7.0
  dartz: ^0.10.1

  # States
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6

  # Regular
  shared_preferences: ^2.3.5
  flutter_svg: ^2.0.16
  fl_chart: ^0.69.0

  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/
